# Basic Numpy Exercises 

### Institue of Applied AI Engineers

#### 1. Create a uniform subdivision of the interval -1.3 to 2.5 with 64 subdivisions.

In [1]:
import numpy as np
x=np.linspace(-1.3,205,64)
x

array([  -1.3       ,    1.97460317,    5.24920635,    8.52380952,
         11.7984127 ,   15.07301587,   18.34761905,   21.62222222,
         24.8968254 ,   28.17142857,   31.44603175,   34.72063492,
         37.9952381 ,   41.26984127,   44.54444444,   47.81904762,
         51.09365079,   54.36825397,   57.64285714,   60.91746032,
         64.19206349,   67.46666667,   70.74126984,   74.01587302,
         77.29047619,   80.56507937,   83.83968254,   87.11428571,
         90.38888889,   93.66349206,   96.93809524,  100.21269841,
        103.48730159,  106.76190476,  110.03650794,  113.31111111,
        116.58571429,  119.86031746,  123.13492063,  126.40952381,
        129.68412698,  132.95873016,  136.23333333,  139.50793651,
        142.78253968,  146.05714286,  149.33174603,  152.60634921,
        155.88095238,  159.15555556,  162.43015873,  165.7047619 ,
        168.97936508,  172.25396825,  175.52857143,  178.8031746 ,
        182.07777778,  185.35238095,  188.62698413,  191.90158

#### 2. Generate an array of length  3n  filled with the cyclic pattern 1, 2, 3.

In [16]:
import numpy as np
x=np.array([1,2,3])
np.resize(x,30)


array([1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3, 1, 2,
       3, 1, 2, 3, 1, 2, 3])

#### 3. Create an array of the first 10 odd integers.

In [6]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

#### 4. Create a 10 x 10 arrays of zeros and then "frame" it with a border of ones.

In [27]:
A=np.zeros([10,10])
A[:,0]=1
A[0,:]=1
A[9,:]=1
A[:,9]=1
A

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]])

#### 5. Create an 8 x 8 array with a checkerboard pattern of zeros and ones using a slicing+striding approach.

In [29]:
Z = np.zeros([8,8])
Z[1::2,::2] = 1
Z[::2,1::2] = 1
Z

array([[ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  1.,  0.,  1.,  0.,  1.],
       [ 1.,  0.,  1.,  0.,  1.,  0.,  1.,  0.]])